version: 2.1

jobs:
  build:
    environment:
      VERSION: 1.20.2
      USE_SYSTEM_FPM: true
    machine:
      image: ubuntu-2204:2023.07.1
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Ubuntu Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y node-rimraf ruby-full rpm squashfs-tools

      - run:
          name: Install FPM
          command: gem install fpm

      - run:
          name: Remove phantomjs dependencies
          command: |
            sed -i '/"@playwright\/test".*/d' package.json
            sed -i '/"electron-icon-maker".*/d' packages/bruno-electron/package.json
            sed -i 's/"electron-builder":\ "23.0.2",/"electron-builder":\ "23.0.2"/' packages/bruno-electron/package.json

      - run:
          name: Install NPM Dependencies
          command: npm install

      - run:
          name: Build bruno node packages
          command: |
            npm run build:graphql-docs
            npm run build:bruno-query
            npm run build:bruno-common
            npm run build:web

      - run:
          name: Build deb package
          command: npm run build:electron:deb

      - store_artifacts:
          name: Upload deb artifact
          path: packages/bruno-electron/out/bruno_1.20.2_arm64_linux.deb
          destination: bruno_1.20.2_arm64_linux.deb

      - run:
          name: Build rpm package
          command: npm run build:electron:rpm

      - store_artifacts:
          name: Upload rpm artifact
          path: packages/bruno-electron/out/bruno_1.20.2_aarch64_linux.rpm
          destination: bruno_1.20.2_aarch64_linux.rpm

      - run:
          name: Build AppImage package
          command: npm run build:electron:linux

      - store_artifacts:
          name: Upload AppImage artifact
          path: packages/bruno-electron/out/bruno_1.20.2_arm64_linux.AppImage
          destination: bruno_1.20.2_arm64_linux.AppImage

workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature/linux-arm64-build
