version: 2.1

jobs:
  build:
    environment:
      VERSION: 1.20.2
      USE_SYSTEM_FPM: true
    machine:
      image: ubuntu-2204:2023.07.1
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Ubuntu Dependencies
          command: sudo apt-get update && sudo apt-get install -y node-rimraf ruby-full rpm squashfs-tools

      - run:
          name: Install FPM
          command: gem install fpm

      # Remove deps needing phantomjs since there is no binary available for arm64
      - run:
          name: Remove playwright/test
          command: sed -i '/"@playwright\/test".*/d' package.json

      - run:
          name: Remove electron-icon-maker
          command: sed -i '/"electron-icon-maker".*/d' packages/bruno-electron/package.json && sed -i 's/"electron-builder":\ "23.0.2",/"electron-builder":\ "23.0.2"/' packages/bruno-electron/package.json

      - run:
          name: Install NPM Dependencies
          command: npm install

      - run:
          name: Build bruno node packages
          command: npm run build:graphql-docs && npm run build:bruno-query && npm run build:bruno-common

      - run:
          name: Build linux packages
          command: npm run build:electron:deb build:electron:rpm build:electron:linux

      - store_artifacts:
          name: Upload deb artifact
          path: packages/bruno-electron/out/bruno_${VERSION}_arm64_linux.deb
          destination: bruno_${VERSION}_arm64_linux.deb

      - store_artifacts:
          name: Upload rpm artifact
          path: packages/bruno-electron/out/bruno_${VERSION}_aarch64_linux.rpm
          destination: bruno_${VERSION}_aarch64_linux.rpm

      - store_artifacts:
          name: Upload AppImage artifact
          path: packages/bruno-electron/out/bruno_${VERSION}_arm64_linux.AppImage
          destination: bruno_${VERSION}_arm64_linux.AppImage

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
