version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Ubuntu Dependencies
          command: sudo apt-get update && sudo apt-get install -y ruby-full squashfs-tools

      - run:
          name: Install FPM
          command: sudo gem install fpm

      - run:
          name: Remove playwright since there is no phantomjs binary available for arm64
          command: npm uninstall @playwright/test

      - run:
          name: Install NPM Dependencies
          command: npm install

      - run:
          name: Build deb package
          command: USE_SYSTEM_FPM=true npm run build:electron:deb

      - run:
          name: Build rpm package
          command: USE_SYSTEM_FPM=true npm run build:electron:rpm

      - run:
          name: Build AppImage package
          command: USE_SYSTEM_FPM=true npm run build:electron:linux

      - store_artifacts:
          path: packages/bruno-app/out/*.deb
          destination: bruno-app-linux-arm64.deb

      - store_artifacts:
          path: packages/bruno-app/out/*.rpm
          destination: bruno-app-linux-arm64.rpm

      - store_artifacts:
          path: packages/bruno-app/out/*.AppImage
          destination: bruno-app-linux-arm64.AppImage

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
