version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Ubuntu Dependencies
          command: sudo apt-get update && sudo apt-get install -y ruby-full rpm squashfs-tools

      - run:
          name: Install FPM
          command: gem install fpm

      # Remove deps needing phantomjs since there is no binary available for arm64
      - run:
          name: Remove playwright/test
          command: sed -i '/"@playwright\/test".*/d' package.json

      - run:
          name: Remove electron-icon-maker
          command: sed -i '/"electron-icon-maker".*/d' packages/bruno-electron/package.json && sed -i 's/"electron-builder":\ "23.0.2",/"electron-builder":\ "23.0.2"/' packages/bruno-electron/package.json

      - run:
          name: Install NPM Dependencies
          command: npm install

      - run:
          name: Build deb package
          command: USE_SYSTEM_FPM=true npm run build:electron:deb

      - run:
          name: Build rpm package
          command: USE_SYSTEM_FPM=true npm run build:electron:rpm

      - run:
          name: Build AppImage package
          command: USE_SYSTEM_FPM=true npm run build:electron:linux

      - store_artifacts:
          path: packages/bruno-app/out/bruno_1.20.2_arm64_linux.deb
          destination: bruno-app-linux-arm64.deb

      - store_artifacts:
          path: packages/bruno-app/out/bruno_1.20.2_arm64_linux.rpm
          destination: bruno-app-linux-arm64.rpm

      - store_artifacts:
          path: packages/bruno-app/out/*.AppImage
          destination: bruno-app-linux-arm64.AppImage

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
