name: Build and Release Electron App

on:
  push:
    branches:
      - feature/linux-arm64-build

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            docker_image: ""
          - arch: arm64
            docker_image: arm64v8/ubuntu:latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Ubuntu Dependencies
        run: sudo apt-get update && sudo apt-get install ruby-full squashfs-tools

      - name: Install FPM
        run: sudo gem install fpm

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Electron App
        run: USE_SYSTEM_FPM=true npm run build:electron

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bruno-app-linux-${{ matrix.arch }}.deb
          path: packages/bruno-app/out/*.{deb,rpm,AppImage}
